# Generated by Django 6.0.6 on 2026-06-13 16:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sim_type', models.CharField(choices=[('double_slit', 'Double Slit Experiment'), ('particle_box', 'Particle in a Box'), ('wavefunction', 'Wavefunction Evolution'), ('tunneling', 'Quantum Tunneling'), ('harmonic', 'Quantum Harmonic Oscillator'), ('hydrogen', 'Hydrogen Atom')], max_length=30)),
                ('parameters', models.JSONField(default=dict)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'simulation_results',
            },
        ),
    ]
