# Generated by Django 6.0.6 on 2026-06-13 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='simulationresult',
            index=models.Index(fields=['user', 'sim_type'], name='simulation__user_id_8aabaf_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationresult',
            index=models.Index(fields=['status'], name='simulation__status_7e735d_idx'),
        ),
    ]
