# Generated by Django 6.0.6 on 2026-06-13 16:28

import apps.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#4F46E5', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'concept_categories',
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.TextField(max_length=500, validators=[apps.core.validators.validate_no_script])),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='concepts/thumbs/')),
                ('related_simulation', models.CharField(blank=True, max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concepts', to='concepts.category')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='unlocks', to='concepts.concept')),
            ],
            options={
                'db_table': 'concepts',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ConceptContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('explanation', models.TextField(validators=[apps.core.validators.validate_no_script])),
                ('math_derivation', models.TextField(blank=True, validators=[apps.core.validators.validate_no_script])),
                ('key_equations', models.JSONField(default=list)),
                ('further_reading', models.JSONField(default=list)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='concepts.concept')),
            ],
            options={
                'db_table': 'concept_contents',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='ConceptLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation', models.CharField(choices=[('prerequisite', 'Prerequisite'), ('related', 'Related'), ('extension', 'Extension'), ('application', 'Application')], default='related', max_length=20)),
                ('weight', models.FloatField(default=1.0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='concepts.concept')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='concepts.concept')),
            ],
            options={
                'db_table': 'concept_links',
            },
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['slug'], name='concepts_slug_0d5a9c_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['difficulty'], name='concepts_difficu_172c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=models.Index(fields=['category', 'order'], name='concepts_categor_2b211b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conceptcontent',
            unique_together={('concept', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='conceptlink',
            unique_together={('source', 'target')},
        ),
    ]
