# Generated by Django 6.0.6 on 2026-06-29 17:26

import apps.core.validators
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latex', models.TextField(validators=[apps.core.validators.validate_no_script])),
                ('description', models.TextField(blank=True, validators=[apps.core.validators.validate_no_script])),
                ('symbols', models.JSONField(default=dict)),
                ('derivation_steps', models.JSONField(default=list)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'concept_formulas',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='concept',
            name='history',
            field=models.TextField(blank=True, validators=[apps.core.validators.validate_no_script]),
        ),
        migrations.AddField(
            model_name='concept',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='concept',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='concept_search_gin'),
        ),
        migrations.AddField(
            model_name='formula',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='concepts.concept'),
        ),
    ]
