# Generated by Django 6.0.6 on 2026-06-30 15:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0002_formula_alter_category_options_category_order_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTopicProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('bookmarked', models.BooleanField(default=False)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='concepts.concept')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_topic_progress',
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['user', 'bookmarked'], name='user_topic__user_id_9b0407_idx')],
                'unique_together': {('user', 'concept')},
            },
        ),
    ]
