# Generated by Django 6.0.6 on 2026-07-01 05:39

import apps.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0003_usertopicprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('definition', models.TextField(validators=[apps.core.validators.validate_no_script])),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glossary_terms', to='concepts.concept')),
            ],
            options={
                'db_table': 'glossary_terms',
                'ordering': ['term'],
                'indexes': [models.Index(fields=['slug'], name='glossary_te_slug_110dfd_idx')],
            },
        ),
    ]
