# Generated by Django 6.0.6 on 2026-07-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0004_glossaryterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='track',
            field=models.CharField(choices=[('quantum-physics', 'Quantum Physics'), ('quantum-computing', 'Quantum Computing')], db_index=True, default='quantum-physics', max_length=20),
        ),
    ]
